# Generated by Django 3.1.6 on 2021-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member1_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Member1 Phone'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Member2 Phone'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Member3 Phone'),
        ),
    ]
