# Generated by Django 3.1.6 on 2021-03-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_teamname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='teamname',
            new_name='team',
        ),
    ]
