# Generated by Django 3.1.6 on 2021-03-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_auto_20210308_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='profile',
        ),
    ]
