# Generated by Django 3.1.6 on 2021-03-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_user'),
        ('response', '0007_auto_20210324_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
