# Generated by Django 3.1.6 on 2021-03-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0008_response_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
