# Generated by Django 3.1.6 on 2021-03-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0011_auto_20210324_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='teamname',
            new_name='user',
        ),
    ]
